name: Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.6-alpine
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run tests
        run: make coverage
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/postgres?sslmode=disable
          NAME_PREFIX: test
      - name: Report Coverage
        run: |
          go get github.com/schrej/godacov
          godacov -t ${{ secrets.CODACY_PROJECT_TOKEN }} -r ./cover.out -c ${GITHUB_SHA}